### ISSUE TITLE
Please deactivate code paths that are not used by flow_ebos.

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#161]
I keep wasting a lot of time chasing errors in parts of ebos that are/should not even used by flow_ebos (according to both @dr-robertk and @andlaus). See #143.

Is it not possible to make sure that only that parts are set up that will be used later on when using flow_ebos?

e.g. this part:
```
(gdb) bt
#0  0x00007ffff148f067 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff1490448 in __GI_abort () at abort.c:89
#2  0x00007ffff1488266 in __assert_fail_base (
    fmt=0x7ffff15c0f18 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0xe9c988 "checkPosition_.find( id ) == checkPosition_.end()", 
    file=file@entry=0xea9328 "/home/mblatt/src/dune/opm/ewoms/ebos/collecttoiorank.hh", line=line@entry=127, 
    function=function@entry=0xeb9f00 <Ewoms::CollectDataToIORank<Ewoms::EclCpGridManager<Ewoms::Properties::TTag::EclFlowProblem> >::DistributeIndexMapping::DistributeIndexMapping(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&)::__PRETTY_FUNCTION__> "Ewoms::CollectDataToIORank<GridManager>::DistributeIndexMapping::DistributeIndexMapping(const std::vector<int>&, const std::vector<int>&, Ewoms::CollectDataToIORank<GridManager>::IndexMapType&, Ewoms:"...) at assert.c:92
#3  0x00007ffff1488312 in __GI___assert_fail (
    assertion=0xe9c988 "checkPosition_.find( id ) == checkPosition_.end()", 
    file=0xea9328 "/home/mblatt/src/dune/opm/ewoms/ebos/collecttoiorank.hh", 
    line=127, 
    function=0xeb9f00 <Ewoms::CollectDataToIORank<Ewoms::EclCpGridManager<Ewoms:---Type <return> to continue, or q <return> to quit---
:Properties::TTag::EclFlowProblem> >::DistributeIndexMapping::DistributeIndexMapping(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> >&, std::vector<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >&)::__PRETTY_FUNCTION__> "Ewoms::CollectDataToIORank<GridManager>::DistributeIndexMapping::DistributeIndexMapping(const std::vector<int>&, const std::vector<int>&, Ewoms::CollectDataToIORank<GridManager>::IndexMapType&, Ewoms:"...) at assert.c:101
#4  0x0000000000b7e7b2 in Ewoms::CollectDataToIORank<Ewoms::EclCpGridManager<Ewoms::Properties::TTag::EclFlowProblem> >::DistributeIndexMapping::DistributeIndexMapping (this=0x7fffffffd270, 
    globalIndex=std::vector of length 300, capacity 300 = {...}, 
    distributedGlobalIndex=std::vector of length 174, capacity 174 = {...}, 
    localIndexMap=std::vector of length 174, capacity 174 = {...}, 
    indexMaps=std::vector of length 2, capacity 2 = {...})
    at /home/mblatt/src/dune/opm/ewoms/ebos/collecttoiorank.hh:127
#5  0x0000000000b42ae0 in Ewoms::CollectDataToIORank<Ewoms::EclCpGridManager<Ewoms::Properties::TTag::EclFlowProblem> >::CollectDataToIORank (this=0x1655da8, 
    gridManager=...)
    at /home/mblatt/src/dune/opm/ewoms/ebos/collecttoiorank.hh:270
#6  0x0000000000b017fe in Ewoms::EclWriter<Ewoms::Properties::TTag::EclFlowProblem>::EclWriter (this=0x1655d20, simulator=...)
    at /home/mblatt/src/dune/opm/ewoms/ebos/eclwriter.hh:139
---Type <return> to continue, or q <return> to quit---
#7  0x0000000000abf02b in Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowProblem>::EclProblem (this=0x163de10, simulator=...)
    at /home/mblatt/src/dune/opm/ewoms/ebos/eclproblem.hh:312
#8  0x0000000000a81f9b in Ewoms::Simulator<Ewoms::Properties::TTag::EclFlowProblem>::Simulator (this=0x15ca810, verbose=false)
    at /home/mblatt/src/dune/opm/ewoms/ewoms/common/simulator.hh:132
#9  0x0000000000a60332 in Opm::FlowMainEbos::setupEbosSimulator (
    this=0x7fffffffd9e0)
    at /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/FlowMainEbos.hpp:374
#10 0x0000000000a5dedc in Opm::FlowMainEbos::execute (this=0x7fffffffd9e0, 
    argc=3, argv=0x7fffffffdbc8)
    at /home/mblatt/src/dune/opm/opm-simulator/opm/autodiff/FlowMainEbos.hpp:116
#11 0x00000000009f55a2 in main (argc=3, argv=0x7fffffffdbc8)
    at /home/mblatt/src/dune/opm/opm-simulator/examples/flow_ebos.cpp:38
```

**Comment by andlaus** [comment]
this issue is a bit too unspecific to fix it. closing it for now.
