### ISSUE TITLE
unknown command line parameter results in uncaught exception

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#385]
If I run
```
flow --bla
```
ewoms throws `std::out_of_range`:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 1) > this->size() (which is 0)

Thread 1 "flow" received signal SIGABRT, Aborted.__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) up
#1  0x00007ffff6cee2f1 in __GI_abort () at abort.c:79
79	abort.c: Datei oder Verzeichnis nicht gefunden.
(gdb) 
#2  0x00007ffff6f4b943 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#3  0x00007ffff6f51896 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#4  0x00007ffff6f518d1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#5  0x00007ffff6f51b04 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#6  0x00007ffff6f4d851 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) 
#7  0x00005555575b0d84 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_check (this=0x7fffffffd1a0, __pos=1, 
    __s=0x555557e3a30a "basic_string::substr") at /usr/include/c++/8/bits/basic_string.h:302
302		  __throw_out_of_range_fmt(__N("%s: __pos (which is %zu) > "
(gdb) 
#8  0x00005555575b9338 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr (this=0x7fffffffd1a0, __pos=1, __n=18446744073709551615)
    at /usr/include/c++/8/bits/basic_string.h:2817
2817				    _M_check(__pos, "basic_string::substr"), __n); }
(gdb) 
#9  0x000055555689872f in Ewoms::Parameters::parseCommandLineOptions<Ewoms::Properties::TTag::FlowEarlyBird, int (std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int, char const**, int, int)>(int, char const**, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int ( const&)(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int, char const**, int, int)) (argc=2, 
    argv=0x7fffffffe028, 
    helpPreamble="Usage: /home/mblatt/src/dune/opm-2.6/opm-simulators/opm-parallel-debug/bin/flow [OPTIONS] [ECL_DECK_FILENAME]\nFlow, an advanced reservoir simulator for ECL-decks provided by the Open Porous Media proj"..., posArgCallback=
    @0x5555568978cb: {int (std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > &, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > &, int, const char **, int, int)} 0x5555568978cb <Ewoms::EclProblem<Ewoms::Properties::TTag::FlowEarlyBird>::handlePositionalParameter(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int, char const**, int, int)>) at /home/mblatt/src/dune/opm-2.6/ewoms/ewoms/common/parametersystem.hh:711
711	        paramValue = s.substr(1);
(gdb) p s
$1 = ""
(gdb) 
```
```

**Comment by andlaus** [comment]
that's because the parsing code currently assumes the presence of an equals sign. The behaviour is indeed unintended, but I'm not sure what is supposed to be done if some random garbage is passed on the command line...

**Comment by andlaus** [comment]
this should be fixed now. at least the discussion seems to have concluded.
